# Numpy란? 
### 과학 계산을 위한 라이브러리로서 다차원 배열을 처리하는데 필요한 여러 유용한 기능 제공
Numpy 라이브러리 안에는 다차원배열을 지원하는 클래스 존재 -> **numpy.ndarray**
- 배열은 동일한 타입값을 가짐
- 다(N) ~ 차원 형태로 구성
- 배열의 차원  : rank
- 각 차원의 크기 : shape

* Numpy 패키지 설치 명령어 : **pip install numpy**

In [ ]:
import numpy as np

##  1. 배열 생성


*   배열 생성 함수 : np.array()
*   배열 생성 유용 함수 : np.arange(start, stop)
*   배열 차원 변경 함수 : np.ndarray.reshape(행, 열)

In [ ]:
arr1 = np.array([1,2,3,4,5]) 
arr2 = np.array([[1,2,3],[4,5,6]])

# 0이상 100미만까지 10씩 차이나게 생성 
print(np.arange(0,100 ,10))
# 0이상 1미만까지 0.1씩 차이나게 생성
print(np.arange(0,1,0.1))

[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [97]:
# reshape() -> 배열 크기 설정
arg_arr = np.arange(1,51) 
arg_arr = arg_arr.reshape(5,10)
print(arg_arr)
print()
print(np.arange(0,100 ,10).reshape(2,5))
print()
print(np.arange(0,1,0.1).reshape(5,2))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

[[ 0 10 20 30 40]
 [50 60 70 80 90]]

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]]


In [ ]:
# 모든 원소를 1차원으로 변경
print(arg_arr.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]



* 0으로 구성된 N차원 배열 생성 : np.zeros(shape)
* 1로 구성된 N차원 배열 생성 : np.ones(shape)
* 초기화 되지 않은 N차원 배열 생성 : np.empty(shape)


In [ ]:
arr_zero = np.zeros((2,4))
print("zeros: ", arr_zero)

arr_one = np.ones((3,2))
print("ones: ", arr_one)

arr_empty = np.empty((2,2))
print("empty: ", arr_empty)

zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
empty:  [[4.65537856e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]





## 2. 배열 속성





In [ ]:
# 배열의 크기
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [ ]:
# 배열 요소 개수(배열 사이즈)
print(arr1.size)
print(arr2.size)

5
6


In [ ]:
# 배열 데이터 타입 확인
print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [ ]:
# 배열 차원(rank) 확인
print(arr1.ndim)
print(arr2.ndim)

1
2


## 3. 데이터 접근하기



###  슬라이싱



In [ ]:
arr = np.arange(1,51).reshape(5,10)
arr.ndim

2

In [ ]:
# 1번째 행까지와 모든 열에 접근
print(arr[0:2])
print()
print(arr[0:2,:])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
# 1번째 행까지와 7번째열부터 끝열까지 접근
print(arr[0:2, 7:])

[[ 8  9 10]
 [18 19 20]]


In [ ]:
print(arr[2:,2:7])

[[23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]]



### 정수 인덱싱

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr2[0])
print(arr2[1]) 

[1 2 3]
[4 5 6]


In [ ]:
print(arr2[0][0])
print(arr2[1][2])
print(arr2[1][0])

1
6
4


In [ ]:
print(arr2[1,2])
print(arr2[0,2])

6
3


In [ ]:
print(arr2[[0,1,1],[1,0,2]])

[2 4 6]


### 불리언 인덱싱


In [ ]:
arr2 = np.array([[1,2,3,4,5],[55,0,60,80,90]])
arr2

array([[ 1,  2,  3,  4,  5],
       [55,  0, 60, 80, 90]])

In [ ]:
print(arr2[1])
print(arr2[1] != 0)

[55  0 60 80 90]
[ True False  True  True  True]


In [ ]:
# 0이 아닌 요솟값에 접근
arr2[1][arr2[1] != 0]

array([55, 60, 80, 90])

In [ ]:
# 짝수 요솟값에 접근
arr2[0:][arr2[0:] % 2 == 0]

array([ 2,  4,  0, 60, 80, 90])

In [ ]:
arr2[0:][arr2[0:] >= 70]

array([80, 90])

## 3. 배열 연산

In [ ]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[3,4],[5,6]])

### 기본연산

In [ ]:
print(arr3 + 3)

[[4 5]
 [6 7]]


In [ ]:
print(arr3/2.0)

[[0.5 1. ]
 [1.5 2. ]]


In [ ]:
print(arr3+arr4)

[[ 4  6]
 [ 8 10]]


In [ ]:
print(arr3*arr4 )

[[ 3  8]
 [15 24]]


In [ ]:
np.array([2,3,4]+[3,5,7])

array([2, 3, 4, 3, 5, 7])

###  행렬 연산

In [ ]:
np.dot(arr3,arr4)

array([[13, 16],
       [29, 36]])

In [ ]:
print(arr3 @ arr4)

[[13 16]
 [29 36]]


## 4. 배열 관련 유용한 함수

In [ ]:
print("arr3:", arr3)
print("arr4:", arr4)

arr3: [[1 2]
 [3 4]]
arr4: [[3 4]
 [5 6]]


In [ ]:
arr5 = np.array([[3,1,2,7],[9,7,2,0]])
print(arr5.max())
print(arr5.min())
print(arr5.argmax())  # 모든 요소 중 최댓값의 인덱스
print(arr5.argmin())  # 모든 요소 중 최소값의 인덱스
print(arr5.cumsum())  # 누적합

9
0
4
7
[ 3  4  6 13 22 29 31 31]


In [ ]:
for i in arr5:
  print(i)

[3 1 2 7]
[9 7 2 0]


In [ ]:
for i in arr5.flat:
  print(i, end = ' ')

3 1 2 7 9 7 2 0 

In [ ]:
# 합
print(np.sum(arr3))
print(arr4.sum())

10
18


In [ ]:
# 제곱근
print(np.sqrt(arr3))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [98]:
# 평균
np.mean(arr3)

2.5